apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: POST

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: '"traceId"\s*:\s*"([a-f0-9]+)"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: View in Jaeger
        - datasourceUid: jaeger
          matcherRegex: "traceId=([a-f0-9]+)"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: View in Jaeger

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{namespace="event-ledger"} | json | traceId="$${__span.traceId}"'
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
